ekf_filter_node:
  ros__parameters:
    use_sim_time: true
    frequency: 30.0
    sensor_timeout: 0.1

    two_d_mode: true
    publish_tf: true
    transform_tolerance: 0.1      # allow up to 100ms delay

    # ─── Correct frame-ID parameters ────────────────────────
    world_frame_id: map
    odom_frame_id: odom
    base_link_frame_id: wamv/base_link

    # ─── Odom input ─────────────────────────────────────────
    odom0: /wamv/odom
    odom0_config: [true, true, false,   # pos x,y,z
                   false, true, true,   # rot roll,pitch,yaw
                   false, false, false, # vel x,y,z
                   false, false, false, # ang vel x,y,z
                   false, false, false] # lin accel x,y,z

    # ─── IMU input ──────────────────────────────────────────
    imu0: /wamv/sensors/imu/imu/data
    imu0_config: [false, false, false,  # no pos
                  false, false, false,  # no orientation
                  true,  true,  true,   # fuse angular velocity
                  true,  true,  true,   # fuse linear acceleration
                  false, false, false]  # ignore mag field
