ekf_local:
  ros__parameters:
    frequency: 30.0
    publish_tf: true
    print_diagnostics: true
    two_d_mode: true
    map_frame: map
    odom_frame: odom
    base_link_frame: wamv/wamv/base_link
    world_frame: odom
    use_control: false
    odom_topic: /odometry/local
    imu0: /wamv/sensors/imu/imu/data
    imu0_config: [false, false, false,  # pos
                  true, true, false,  # vel
                  false, false, false,    # orientation (roll, pitch, yaw)
                  true, true, true, 
                  true, true, true]   # ang vel (roll, pitch, yaw)
                  
    imu0_nodelay: false
    imu0_differential: true
    imu0_relative: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true
    # Covariances (all diagonal entries at least 1e-6)
    process_noise_covariance: [1e-3, 1e-3, 1e-3, 0.3, 0.3, 0.01, 0.5, 0.5, 0.1, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3]

    
    initial_estimate_covariance: [1e-9, 1e-9, 1e-9, 1.0, 1.0, 1e-9, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]


ekf_global:
  ros__parameters:
    provide_odom_frame: false 
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    transform_time_offset: 0.0
    map_frame: map
    odom_frame: odom
    base_link_frame: wamv/wamv/base_link
    world_frame: map
    publish_tf: true
    print_diagnostics: true
    debug: false
    odom_topic: /odometry/global
    # GPS odometry input
    odom1: /odometry/gps
    odom1_config: [true, true, false,  # x, y
                   false, false, false,  # z, vx, vy
                   false, false, false,  # vz, roll, pitch
                   false, false, false,   # yaw
                   false, false, false]
    odom1_queue_size: 10
    odom1_nodelay: true
    odom1_differential: false
    odom1_relative: false
    # IMU
    imu0: /wamv/sensors/imu/imu/data
    imu0_config: [false, false, false,  # pos
                  false, false, false,  # vel
                  false, false, false,    # orientation (roll, pitch, yaw)
                  true, true, true,    # ang vel (roll, pitch, yaw)
                  true, true, true]
    use_control: false 
    imu0_nodelay: true
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true
    # Covariances (all diagonal entries at least 1e-6)
    
    process_noise_covariance: [1.0, 1.0, 1e-3, 0.3, 0.3, 0.01, 0.5, 0.5, 0.1, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3]

    initial_estimate_covariance: [1.0, 1.0, 1e-9, 1.0, 1.0, 1e-9, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]


navsat_transform:
  ros__parameters:
    use_sim_time: True
    frequency: 30.0
    zero_altitude: true
    use_odometry_yaw: true
    wait_for_datum: false
    broadcast_cartesian_transform: false
    publish_filtered_gps: true
    world_frame_id: map
    gnss_frame_id: wamv/wamv/gps_wamv_link/navsat
    base_link_frame_id: wamv/wamv/base_link