# navsat_transform:
#   ros__parameters:
#     use_sim_time: True
#     frewuency: 30.0
#     zero_altitude: true
#     use_odometry_yaw: true
#     wait_for_datum: false
#     broadcast_cartesian_transform: true
#     world_frame_id: map
#     gnss_frame_id: wamv/wamv/gps_wamv_link/navsat
#     base_link_frame_id: wamv/wamv/base_link
   