slam_toolbox:
  ros__parameters:
    use_sim_time: true

    # Frame names must match your TF tree
    map_frame: map
    odom_frame: odom
    base_frame: wamv/base_link

    # Lidar scan input
    scan_topic: /wamv/sensors/lidars/laser_down/scan

    # How big your map pixels are (meters per cell)
    resolution: 0.05

    # Publish the map every N seconds
    publish_period_sec: 1.0

    # Range limits on the lidar
    minimum_range: 0.12
    maximum_range: 30.0

    # Enable loop closure?
    use_online_correlative_scan_matching: false

    # Pose graph optimization
    optimize_every_n_nodes: 20
    max_laser_scans: 10

    # Submap parameters (for online_async mode)
    submap_size: 20.0               # meters
    submap_publish_period_sec: 0.5

    # Time to wait for transforms
    transform_publish_period: 0.05
