slam_toolbox:
  ros__parameters:
    use_sim_time: true
    mode: online_async
    map_file_name: ""                # live only

    # TF frames
    map_frame: map
    odom_frame: odom
    base_frame: wamv/wamv/base_link/laser_down

    # ↓↓ only your downward LiDAR ↓↓
    scan_topic: /wamv/sensors/lidars/laser_down/scan
    resolution: 0.05

    # —— CORRECT PUBLISH PARAMETERS ——
    map_publish_period_sec:           0.5   # republish /map twice a second
    transform_publish_period_sec:     0.05  # republish map→odom TF 

    # laser limits (match URDF)
    min_laser_range: 0.1
    max_laser_range: 20.0

    message_filter_queue_size: 100
    use_online_correlative_scan_matching: false

    # —— FORCE FIRST‐SCAN OPTIMIZE & PUBLISH ——
    optimize_every_n_nodes: 1
    max_laser_scans:       1

    submap_size: 5.0
    submap_publish_period_sec: 0.5